"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import {
  Sparkles,
  RefreshCw,
  Loader2,
  Check,
  X,
  PenLine,
  AlertTriangle,
  Wand2,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { AppHeader } from "@/components/app-header";

type ThemeCheck = {
  alerte: boolean;
  niveau: "aucun" | "attention" | "repetition";
  message: string;
  posts_similaires: string[];
  angle_alternatif: string;
};

type IdeaAngle =
  | "retour_experience"
  | "prise_de_position"
  | "conseil"
  | "histoire"
  | "observation";

type GeneratedIdea = {
  title: string;
  angle: IdeaAngle;
  memory_anchor: string;
  zone: string;
};

const ANGLE_LABELS: Record<IdeaAngle, string> = {
  retour_experience: "Retour d'expérience",
  prise_de_position: "Prise de position",
  conseil: "Conseil concret",
  histoire: "Histoire personnelle",
  observation: "Observation",
};

export default function IdeasPage() {
  const router = useRouter();
  const searchParams = useSearchParams();
  const preselectedZone = searchParams.get("zone")?.trim() ?? "";
  const [ideas, setIdeas] = useState<GeneratedIdea[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [selected, setSelected] = useState<GeneratedIdea | null>(null);
  const [checking, setChecking] = useState(false);
  const [theme, setTheme] = useState<ThemeCheck | null>(null);
  const [remainingIdeaGenerations, setRemainingIdeaGenerations] = useState<
    number | null
  >(null);
  const lastTapRef = useRef<{ idea: string; time: number } | null>(null);
  const autoGeneratedZoneRef = useRef<string | null>(null);

  // Analyse l'historique thématique quand on sélectionne une idée.
  async function selectIdea(idea: GeneratedIdea) {
    setSelected(idea);
    setTheme(null);
    setChecking(true);
    try {
      const res = await fetch("/api/theme-check", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ idea: idea.title }),
      });
      const data = await res.json();
      if (res.ok) setTheme(data);
    } finally {
      setChecking(false);
    }
  }

  // Navigue vers l'éditeur, avec un angle imposé optionnel.
  function goWrite(angle?: string) {
    if (!selected) return;
    const base = `/write?idea=${encodeURIComponent(selected.title)}`;
    router.push(angle ? `${base}&angle=${encodeURIComponent(angle)}` : base);
  }

  function goWriteIdea(idea: GeneratedIdea, angle?: string) {
    const base = `/write?idea=${encodeURIComponent(idea.title)}`;
    router.push(angle ? `${base}&angle=${encodeURIComponent(angle)}` : base);
  }

  function handleIdeaTap(idea: GeneratedIdea) {
    const now = Date.now();
    const lastTap = lastTapRef.current;
    const isDoubleTap =
      lastTap?.idea === idea.title && now - lastTap.time < 350;

    if (isDoubleTap) {
      lastTapRef.current = null;
      goWriteIdea(idea);
      return;
    }

    lastTapRef.current = { idea: idea.title, time: now };
    selectIdea(idea);
  }

  const generateIdeas = useCallback(async (zone?: string) => {
    setLoading(true);
    setError(null);
    setSelected(null);
    setTheme(null);
    try {
      const res = await fetch("/api/ideas", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ zone: zone?.trim() || undefined }),
      });
      const data = await res.json();
      if (!res.ok) {
        throw new Error(data.error || "Une erreur est survenue.");
      }
      setIdeas(data.ideas);
      if (typeof data.remainingIdeaGenerations === "number") {
        setRemainingIdeaGenerations(data.remainingIdeaGenerations);
      }
    } catch (err) {
      setError(err instanceof Error ? err.message : "Erreur inconnue.");
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    if (!preselectedZone) return;
    if (autoGeneratedZoneRef.current === preselectedZone) return;
    autoGeneratedZoneRef.current = preselectedZone;
    generateIdeas(preselectedZone);
  }, [generateIdeas, preselectedZone]);

  return (
    <main className="min-h-screen overflow-x-hidden bg-card pb-28 text-foreground md:pb-0">
      <AppHeader />

      <section className="mx-auto w-full max-w-5xl overflow-x-hidden p-4 md:px-6 md:py-10 lg:px-8">
        <div className="text-center">
          <h1 className="text-2xl font-medium tracking-tight md:text-3xl lg:text-4xl">
            Tes idées de posts
          </h1>
          <p className="mx-auto mt-2 max-w-xl text-sm text-muted-foreground md:text-base">
            Echo te propose 9 angles accrocheurs adaptés à ton métier et ta
            cible. Clique sur celui qui t&apos;inspire.
          </p>

          {preselectedZone && (
            <div className="mx-auto mt-5 flex max-w-xl flex-col items-center justify-center gap-3 rounded-2xl border border-primary/30 bg-primary/5 p-4 text-sm text-foreground sm:flex-row">
              <span>
                Génération centrée sur :{" "}
                <span className="font-semibold text-primary">
                  {preselectedZone}
                </span>
              </span>
              <button
                type="button"
                onClick={() => {
                  autoGeneratedZoneRef.current = null;
                  router.push("/ideas");
                }}
                className="inline-flex touch-manipulation items-center gap-1 text-muted-foreground underline-offset-4 hover:text-foreground hover:underline"
              >
                Modifier le filtre
                <X className="h-3.5 w-3.5" />
              </button>
            </div>
          )}

          <div className="mt-6">
            <Button
              onClick={() => generateIdeas(preselectedZone)}
              disabled={loading}
              size="lg"
              className="w-full sm:w-auto"
            >
              {loading ? (
                <>
                  <Loader2 className="h-4 w-4 animate-spin" />
                  Génération en cours…
                </>
              ) : ideas.length > 0 ? (
                <>
                  <RefreshCw className="h-4 w-4" />
                  Régénérer mes idées
                </>
              ) : (
                <>
                  <Sparkles className="h-4 w-4" />
                  Générer mes idées de posts
                </>
              )}
            </Button>
          </div>
        </div>

        {error && (
          <p className="mx-auto mt-6 max-w-xl rounded-lg bg-destructive/10 px-4 py-3 text-center text-sm text-destructive">
            {error}
          </p>
        )}

        {remainingIdeaGenerations !== null && remainingIdeaGenerations <= 5 && (
          <p className="mx-auto mt-4 max-w-xl rounded-lg border border-border bg-background px-4 py-3 text-center text-sm text-muted-foreground">
            Il te reste {remainingIdeaGenerations} génération
            {remainingIdeaGenerations > 1 ? "s" : ""} d&apos;idées aujourd&apos;hui.
          </p>
        )}

        {/* Grille 3x3 des idées */}
        {ideas.length > 0 && (
          <div className="mt-6 grid w-full max-w-full grid-cols-1 gap-3 overflow-hidden md:mt-10 md:grid-cols-2 md:gap-4 lg:grid-cols-3">
            {ideas.map((idea, index) => {
              const isSelected = selected?.title === idea.title;
              return (
                <button
                  key={`${idea.title}-${index}`}
                  onClick={() => handleIdeaTap(idea)}
                  className={`group relative flex min-h-[132px] w-full max-w-full touch-manipulation flex-col justify-between overflow-hidden rounded-2xl border p-4 text-left transition md:min-h-[140px] md:p-5 ${
                    isSelected
                      ? "border-primary bg-primary/5 ring-2 ring-primary"
                      : "border-border bg-background hover:border-primary/40 hover:shadow-md"
                  }`}
                >
                  <span className="flex h-7 w-7 items-center justify-center rounded-lg bg-primary/10 text-xs font-bold text-primary">
                    {index + 1}
                  </span>
                  <span className="mt-3 w-fit rounded-full bg-accent px-2.5 py-1 text-xs font-medium text-primary">
                    {ANGLE_LABELS[idea.angle] ?? idea.angle}
                  </span>
                  <p className="mt-3 break-words text-sm font-medium text-foreground md:text-base">
                    {idea.title}
                  </p>
                  {isSelected && (
                    <span className="absolute right-4 top-4 flex h-6 w-6 items-center justify-center rounded-full bg-primary text-primary-foreground">
                      <Check className="h-4 w-4" />
                    </span>
                  )}
                </button>
              );
            })}
          </div>
        )}

        {/* Panneau de l'idée sélectionnée + garde-fou thématique */}
        {selected && (
          <div className="mt-6 max-w-full overflow-hidden rounded-2xl border border-primary/30 bg-background p-4 shadow-sm md:mt-8 md:p-6">
            <p className="text-xs font-medium text-muted-foreground md:text-sm">
              Idée sélectionnée
            </p>
            <p className="mt-1 break-words text-base font-semibold text-foreground md:text-lg">
              {selected.title}
            </p>
            <div className="mt-3 flex flex-wrap gap-2 text-xs">
              <span className="rounded-full bg-accent px-2.5 py-1 font-medium text-primary">
                {ANGLE_LABELS[selected.angle] ?? selected.angle}
              </span>
              <span className="rounded-full border border-border px-2.5 py-1 text-muted-foreground">
                {selected.zone}
              </span>
            </div>

            {checking ? (
              <p className="mt-4 flex items-center gap-2 text-sm text-muted-foreground">
                <Loader2 className="h-4 w-4 animate-spin" />
                Analyse de tes sujets récents…
              </p>
            ) : (
              <>
                {theme && theme.niveau !== "aucun" && (
                  <div
                    className={`mt-4 max-w-full overflow-hidden rounded-xl border p-4 ${
                      theme.niveau === "repetition"
                        ? "border-orange-300 bg-orange-50"
                        : "border-yellow-300 bg-yellow-50"
                    }`}
                  >
                    <div className="flex min-w-0 items-start gap-3">
                      <AlertTriangle
                        className={`mt-0.5 h-5 w-5 shrink-0 ${
                          theme.niveau === "repetition"
                            ? "text-orange-500"
                            : "text-yellow-600"
                        }`}
                      />
                      <div className="min-w-0 flex-1 text-sm">
                        <p
                          className={`font-semibold ${
                            theme.niveau === "repetition"
                              ? "text-orange-800"
                              : "text-yellow-800"
                          }`}
                        >
                          {theme.niveau === "repetition"
                            ? "Ce sujet revient souvent dans tes posts récents"
                            : "Tu as abordé un sujet proche il y a peu"}
                        </p>
                        <p
                          className={`mt-1 ${
                            theme.niveau === "repetition"
                              ? "text-orange-700"
                              : "text-yellow-700"
                          }`}
                        >
                          {theme.message}
                        </p>
                        {theme.posts_similaires?.length > 0 && (
                          <ul className="mt-2 list-disc break-words pl-5 text-muted-foreground">
                            {theme.posts_similaires.map((t, i) => (
                              <li key={i}>{t}</li>
                            ))}
                          </ul>
                        )}
                        {theme.angle_alternatif && (
                          <p className="mt-2 break-words text-foreground">
                            <span className="font-medium">
                              Angle différent :{" "}
                            </span>
                            {theme.angle_alternatif}
                          </p>
                        )}
                      </div>
                    </div>
                  </div>
                )}

                <div className="mt-4 grid gap-3 sm:flex sm:flex-wrap">
                  {theme && theme.niveau !== "aucun" ? (
                    <>
                      <Button
                        variant="outline"
                        onClick={() => goWrite()}
                        className="w-full sm:w-auto"
                      >
                        <PenLine className="h-4 w-4" />
                        Générer quand même
                      </Button>
                      {theme.angle_alternatif && (
                        <Button
                          onClick={() => goWrite(theme.angle_alternatif)}
                          className="w-full sm:w-auto"
                        >
                          <Wand2 className="h-4 w-4" />
                          Utiliser cet angle
                        </Button>
                      )}
                    </>
                  ) : (
                    <Button onClick={() => goWrite()} className="w-full sm:w-auto">
                      <PenLine className="h-4 w-4" />
                      Rédiger ce post
                    </Button>
                  )}
                </div>
              </>
            )}
          </div>
        )}
      </section>
    </main>
  );
}
